{
  "uid" : "b56a9f32c4c76f38",
  "name" : "test__repeated_article_creation",
  "fullName" : "test.test_main.TestConduit#test__repeated_article_creation",
  "historyId" : "50e0661c549e4b8d96fe01018caed7c4",
  "time" : {
    "start" : 1628668922929,
    "stop" : 1628668923096,
    "duration" : 167
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'articles.csv'",
  "statusTrace" : "self = <test_main.TestConduit object at 0x7ffa71307520>\n\n    def test__repeated_article_creation(self):\n        accept_cookies(self.driver)\n        logging_in(self.driver)\n>       with open(\"articles.csv\", \"r\", encoding='utf-8') as csvfile_read:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'articles.csv'\n\ntest/test_main.py:253: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'articles.csv'",
    "statusTrace" : "self = <test_main.TestConduit object at 0x7ffa71307520>\n\n    def test__repeated_article_creation(self):\n        accept_cookies(self.driver)\n        logging_in(self.driver)\n>       with open(\"articles.csv\", \"r\", encoding='utf-8') as csvfile_read:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'articles.csv'\n\ntest/test_main.py:253: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "7eb8e9f8d3f16ed7",
      "name" : "log",
      "source" : "7eb8e9f8d3f16ed7.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "996bba1ec3ef5306",
      "name" : "stderr",
      "source" : "996bba1ec3ef5306.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "test_main"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az83-587"
  }, {
    "name" : "thread",
    "value" : "3806-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_main"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "b56a9f32c4c76f38.json",
  "parameterValues" : [ ]
}